
export const ADD_BUCKET_SUCCESS = 'ADD_BUCKET_SUCCESS';
export const ADD_BUCKET_FAILED = 'ADD_BUCKET_FAILED';


export const SET_BUCKET_SUCCESS = 'SET_BUCKET_SUCCESS';
export const SET_BUCKET_FAILED = 'SET_BUCKET_FAILED';

export const RESET_ERROR = 'RESET_ERROR';
export const SET_ERROR = 'SET_ERROR';


export const SET_SELECTED_BUCKET = 'SET_SELECTED_BUCKET';
export const RESET_SELECTED_BUCKET = 'RESET_SELECTED_BUCKET';



